services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=mhashmi373@gmail.com
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy 

  portfolio:
    image: ghcr.io/maazh10/portfolio:latest
    container_name: portfolio
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=maazh.tech
      - LETSENCRYPT_HOST=maazh.tech

  blog:
    image: ghcr.io/maazh10/blog:latest
    container_name: blog
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=maazh.tech
      - VIRTUAL_PATH=/blog
